version: '3'
services:
  development:
    image: fabiosammy/project-ionic
    command: /usr/bin/sudo /usr/sbin/sshd -D
    ports:
      - "2236:22"
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
    privileged: true
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - ./apps:/var/www
      - ./.home-devel:/home/devel

